// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';
import {mcp} from '../models';

export function Chat(arg1:string):Promise<pipeline.RunResult>;

export function ClearChat():Promise<void>;

export function ListTools():Promise<Array<mcp.Tool>>;
