// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveToolCall(arg1, arg2) {
  return window['go']['main']['App']['ApproveToolCall'](arg1, arg2);
}

export function CancelChat() {
  return window['go']['main']['App']['CancelChat']();
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function ExportConversation(arg1) {
  return window['go']['main']['App']['ExportConversation'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function OpenConversation(arg1) {
  return window['go']['main']['App']['OpenConversation'](arg1);
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}
