// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';
import {main} from '../models';
import {mcp} from '../models';

export function ApproveToolCall(arg1:string,arg2:boolean):Promise<boolean>;

export function CancelChat():Promise<boolean>;

export function Chat(arg1:string):Promise<pipeline.RunResult>;

export function ClearChat():Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function ExportConversation(arg1:string):Promise<string>;

export function GetConversation(arg1:string):Promise<main.Conversation>;

export function ListConversations():Promise<Array<main.ConversationSummary>>;

export function ListTools():Promise<Array<mcp.Tool>>;

export function NewConversation():Promise<main.ConversationSummary>;

export function OpenConversation(arg1:string):Promise<main.Conversation>;

export function RevealPath(arg1:string):Promise<void>;
